FROM library/centos:6

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm \
&& yum install -y \
    npm \
    \
    cmake \
    make \
    gcc \
    gcc-c++ \
    \
    boost-devel \
    \
    qpid-cpp-client-devel \
    \
    qpid-proton-cpp-devel \
    \
&& yum clean all \
&& rm -rf /var/cache/yum
