FROM docker.io/library/fedora:37

RUN dnf install -y \
    npm \
    \
    cmake \
    make \
    gcc \
    gcc-c++ \
    \
    boost-devel \
    \
    qpid-proton-cpp-devel \
    \
&& dnf clean all \
&& rm -rf /var/cache/dnf

RUN npm install -g @bazel/bazelisk
